/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IOmniPayNotifier } from "./IOmniPayNotifier";
export type { OmniPaySubscription } from "./OmniPaySubscription";
