/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IOmniPayNotifierSubInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "notifySubscriptionCancelled"
      | "notifySubscriptionExecuted"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "notifySubscriptionCancelled",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "notifySubscriptionExecuted",
    values: [
      BigNumberish,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "notifySubscriptionCancelled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "notifySubscriptionExecuted",
    data: BytesLike
  ): Result;
}

export interface IOmniPayNotifierSub extends BaseContract {
  connect(runner?: ContractRunner | null): IOmniPayNotifierSub;
  waitForDeployment(): Promise<this>;

  interface: IOmniPayNotifierSubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  notifySubscriptionCancelled: TypedContractMethod<
    [subId: BigNumberish, subscriber: AddressLike, merchant: AddressLike],
    [void],
    "nonpayable"
  >;

  notifySubscriptionExecuted: TypedContractMethod<
    [
      subId: BigNumberish,
      subscriber: AddressLike,
      merchant: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      nextPaymentDue: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "notifySubscriptionCancelled"
  ): TypedContractMethod<
    [subId: BigNumberish, subscriber: AddressLike, merchant: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "notifySubscriptionExecuted"
  ): TypedContractMethod<
    [
      subId: BigNumberish,
      subscriber: AddressLike,
      merchant: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      nextPaymentDue: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
