/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface OmniPaySubscriptionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelSubscription"
      | "createSubscription"
      | "executeSubscription"
      | "nextId"
      | "notifier"
      | "owner"
      | "renounceOwnership"
      | "setNotifier"
      | "subscriptions"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "SubscriptionCancelled"
      | "SubscriptionCreated"
      | "SubscriptionExecuted"
      | "SubscriptionFailed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSubscription",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nextId", values?: undefined): string;
  encodeFunctionData(functionFragment: "notifier", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setNotifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "notifier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNotifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCancelledEvent {
  export type InputTuple = [
    id: BigNumberish,
    subscriber: AddressLike,
    merchant: AddressLike
  ];
  export type OutputTuple = [id: bigint, subscriber: string, merchant: string];
  export interface OutputObject {
    id: bigint;
    subscriber: string;
    merchant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    subscriber: AddressLike,
    merchant: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    interval: BigNumberish,
    nextPaymentDue: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    subscriber: string,
    merchant: string,
    token: string,
    amount: bigint,
    interval: bigint,
    nextPaymentDue: bigint
  ];
  export interface OutputObject {
    id: bigint;
    subscriber: string;
    merchant: string;
    token: string;
    amount: bigint;
    interval: bigint;
    nextPaymentDue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionExecutedEvent {
  export type InputTuple = [
    id: BigNumberish,
    subscriber: AddressLike,
    merchant: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    nextPaymentDue: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    subscriber: string,
    merchant: string,
    token: string,
    amount: bigint,
    nextPaymentDue: bigint
  ];
  export interface OutputObject {
    id: bigint;
    subscriber: string;
    merchant: string;
    token: string;
    amount: bigint;
    nextPaymentDue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionFailedEvent {
  export type InputTuple = [
    id: BigNumberish,
    subscriber: AddressLike,
    merchant: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    id: bigint,
    subscriber: string,
    merchant: string,
    token: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    id: bigint;
    subscriber: string;
    merchant: string;
    token: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OmniPaySubscription extends BaseContract {
  connect(runner?: ContractRunner | null): OmniPaySubscription;
  waitForDeployment(): Promise<this>;

  interface: OmniPaySubscriptionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelSubscription: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  createSubscription: TypedContractMethod<
    [
      merchant: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      intervalSeconds: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  executeSubscription: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "payable"
  >;

  nextId: TypedContractMethod<[], [bigint], "view">;

  notifier: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setNotifier: TypedContractMethod<
    [_notifier: AddressLike],
    [void],
    "nonpayable"
  >;

  subscriptions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, bigint, boolean] & {
        id: bigint;
        subscriber: string;
        merchant: string;
        token: string;
        amount: bigint;
        interval: bigint;
        nextPaymentDue: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelSubscription"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createSubscription"
  ): TypedContractMethod<
    [
      merchant: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      intervalSeconds: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeSubscription"
  ): TypedContractMethod<[id: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "nextId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "notifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setNotifier"
  ): TypedContractMethod<[_notifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscriptions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, bigint, boolean] & {
        id: bigint;
        subscriber: string;
        merchant: string;
        token: string;
        amount: bigint;
        interval: bigint;
        nextPaymentDue: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCancelled"
  ): TypedContractEvent<
    SubscriptionCancelledEvent.InputTuple,
    SubscriptionCancelledEvent.OutputTuple,
    SubscriptionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCreated"
  ): TypedContractEvent<
    SubscriptionCreatedEvent.InputTuple,
    SubscriptionCreatedEvent.OutputTuple,
    SubscriptionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionExecuted"
  ): TypedContractEvent<
    SubscriptionExecutedEvent.InputTuple,
    SubscriptionExecutedEvent.OutputTuple,
    SubscriptionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionFailed"
  ): TypedContractEvent<
    SubscriptionFailedEvent.InputTuple,
    SubscriptionFailedEvent.OutputTuple,
    SubscriptionFailedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SubscriptionCancelled(uint256,address,address)": TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;
    SubscriptionCancelled: TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;

    "SubscriptionCreated(uint256,address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;
    SubscriptionCreated: TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;

    "SubscriptionExecuted(uint256,address,address,address,uint256,uint256)": TypedContractEvent<
      SubscriptionExecutedEvent.InputTuple,
      SubscriptionExecutedEvent.OutputTuple,
      SubscriptionExecutedEvent.OutputObject
    >;
    SubscriptionExecuted: TypedContractEvent<
      SubscriptionExecutedEvent.InputTuple,
      SubscriptionExecutedEvent.OutputTuple,
      SubscriptionExecutedEvent.OutputObject
    >;

    "SubscriptionFailed(uint256,address,address,address,uint256,string)": TypedContractEvent<
      SubscriptionFailedEvent.InputTuple,
      SubscriptionFailedEvent.OutputTuple,
      SubscriptionFailedEvent.OutputObject
    >;
    SubscriptionFailed: TypedContractEvent<
      SubscriptionFailedEvent.InputTuple,
      SubscriptionFailedEvent.OutputTuple,
      SubscriptionFailedEvent.OutputObject
    >;
  };
}
