/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as omniPayCoreSol from "./OmniPayCore.sol";
export type { omniPayCoreSol };
import type * as omniPayNotifierSol from "./OmniPayNotifier.sol";
export type { omniPayNotifierSol };
import type * as omniPaySubscriptionSol from "./OmniPaySubscription.sol";
export type { omniPaySubscriptionSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { OmniPayBridgeStub } from "./OmniPayBridgeStub";
