/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace OmniPayBridgeStub {
  export type CrossChainTransactionStruct = {
    localTxId: BigNumberish;
    payer: AddressLike;
    payee: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    chain: string;
    paymentRef: string;
    timestamp: BigNumberish;
    status: BigNumberish;
  };

  export type CrossChainTransactionStructOutput = [
    localTxId: bigint,
    payer: string,
    payee: string,
    token: string,
    amount: bigint,
    chain: string,
    paymentRef: string,
    timestamp: bigint,
    status: bigint
  ] & {
    localTxId: bigint;
    payer: string;
    payee: string;
    token: string;
    amount: bigint;
    chain: string;
    paymentRef: string;
    timestamp: bigint;
    status: bigint;
  };
}

export interface OmniPayBridgeStubInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addOperator"
      | "authorizedOperators"
      | "completeCrossChainPayment"
      | "completedTransactions"
      | "generateTransactionId"
      | "getCompletedTransaction"
      | "getInitiatedTransaction"
      | "getTransactionStatus"
      | "initiateCrossChainPayment"
      | "initiatedTransactions"
      | "isOperator"
      | "markTransactionFailed"
      | "nextTransactionId"
      | "owner"
      | "removeOperator"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CrossChainPaymentCompleted"
      | "CrossChainPaymentFailed"
      | "CrossChainPaymentInitiated"
      | "OperatorAdded"
      | "OperatorRemoved"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedOperators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeCrossChainPayment",
    values: [
      BigNumberish,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "completedTransactions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "generateTransactionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCompletedTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInitiatedTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateCrossChainPayment",
    values: [
      BigNumberish,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initiatedTransactions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markTransactionFailed",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTransactionId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedOperators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeCrossChainPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completedTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateTransactionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCompletedTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInitiatedTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateCrossChainPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiatedTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOperator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markTransactionFailed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextTransactionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CrossChainPaymentCompletedEvent {
  export type InputTuple = [
    localTxId: BigNumberish,
    payer: AddressLike,
    payee: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    sourceChain: string,
    paymentRef: string
  ];
  export type OutputTuple = [
    localTxId: bigint,
    payer: string,
    payee: string,
    token: string,
    amount: bigint,
    sourceChain: string,
    paymentRef: string
  ];
  export interface OutputObject {
    localTxId: bigint;
    payer: string;
    payee: string;
    token: string;
    amount: bigint;
    sourceChain: string;
    paymentRef: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CrossChainPaymentFailedEvent {
  export type InputTuple = [
    localTxId: BigNumberish,
    payer: AddressLike,
    payee: AddressLike,
    chain: string,
    reason: string
  ];
  export type OutputTuple = [
    localTxId: bigint,
    payer: string,
    payee: string,
    chain: string,
    reason: string
  ];
  export interface OutputObject {
    localTxId: bigint;
    payer: string;
    payee: string;
    chain: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CrossChainPaymentInitiatedEvent {
  export type InputTuple = [
    localTxId: BigNumberish,
    payer: AddressLike,
    payee: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    targetChain: string,
    paymentRef: string
  ];
  export type OutputTuple = [
    localTxId: bigint,
    payer: string,
    payee: string,
    token: string,
    amount: bigint,
    targetChain: string,
    paymentRef: string
  ];
  export interface OutputObject {
    localTxId: bigint;
    payer: string;
    payee: string;
    token: string;
    amount: bigint;
    targetChain: string;
    paymentRef: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorAddedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorRemovedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OmniPayBridgeStub extends BaseContract {
  connect(runner?: ContractRunner | null): OmniPayBridgeStub;
  waitForDeployment(): Promise<this>;

  interface: OmniPayBridgeStubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addOperator: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedOperators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  completeCrossChainPayment: TypedContractMethod<
    [
      localTxId: BigNumberish,
      payer: AddressLike,
      payee: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      sourceChain: string,
      paymentRef: string
    ],
    [void],
    "nonpayable"
  >;

  completedTransactions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint
      ] & {
        localTxId: bigint;
        payer: string;
        payee: string;
        token: string;
        amount: bigint;
        chain: string;
        paymentRef: string;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  generateTransactionId: TypedContractMethod<[], [bigint], "nonpayable">;

  getCompletedTransaction: TypedContractMethod<
    [localTxId: BigNumberish],
    [OmniPayBridgeStub.CrossChainTransactionStructOutput],
    "view"
  >;

  getInitiatedTransaction: TypedContractMethod<
    [localTxId: BigNumberish],
    [OmniPayBridgeStub.CrossChainTransactionStructOutput],
    "view"
  >;

  getTransactionStatus: TypedContractMethod<
    [localTxId: BigNumberish],
    [bigint],
    "view"
  >;

  initiateCrossChainPayment: TypedContractMethod<
    [
      localTxId: BigNumberish,
      payer: AddressLike,
      payee: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      targetChain: string,
      paymentRef: string
    ],
    [void],
    "nonpayable"
  >;

  initiatedTransactions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint
      ] & {
        localTxId: bigint;
        payer: string;
        payee: string;
        token: string;
        amount: bigint;
        chain: string;
        paymentRef: string;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  isOperator: TypedContractMethod<[operator: AddressLike], [boolean], "view">;

  markTransactionFailed: TypedContractMethod<
    [localTxId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  nextTransactionId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeOperator: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addOperator"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedOperators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "completeCrossChainPayment"
  ): TypedContractMethod<
    [
      localTxId: BigNumberish,
      payer: AddressLike,
      payee: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      sourceChain: string,
      paymentRef: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "completedTransactions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint
      ] & {
        localTxId: bigint;
        payer: string;
        payee: string;
        token: string;
        amount: bigint;
        chain: string;
        paymentRef: string;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "generateTransactionId"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getCompletedTransaction"
  ): TypedContractMethod<
    [localTxId: BigNumberish],
    [OmniPayBridgeStub.CrossChainTransactionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getInitiatedTransaction"
  ): TypedContractMethod<
    [localTxId: BigNumberish],
    [OmniPayBridgeStub.CrossChainTransactionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransactionStatus"
  ): TypedContractMethod<[localTxId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "initiateCrossChainPayment"
  ): TypedContractMethod<
    [
      localTxId: BigNumberish,
      payer: AddressLike,
      payee: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      targetChain: string,
      paymentRef: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initiatedTransactions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint
      ] & {
        localTxId: bigint;
        payer: string;
        payee: string;
        token: string;
        amount: bigint;
        chain: string;
        paymentRef: string;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isOperator"
  ): TypedContractMethod<[operator: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "markTransactionFailed"
  ): TypedContractMethod<
    [localTxId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextTransactionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeOperator"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CrossChainPaymentCompleted"
  ): TypedContractEvent<
    CrossChainPaymentCompletedEvent.InputTuple,
    CrossChainPaymentCompletedEvent.OutputTuple,
    CrossChainPaymentCompletedEvent.OutputObject
  >;
  getEvent(
    key: "CrossChainPaymentFailed"
  ): TypedContractEvent<
    CrossChainPaymentFailedEvent.InputTuple,
    CrossChainPaymentFailedEvent.OutputTuple,
    CrossChainPaymentFailedEvent.OutputObject
  >;
  getEvent(
    key: "CrossChainPaymentInitiated"
  ): TypedContractEvent<
    CrossChainPaymentInitiatedEvent.InputTuple,
    CrossChainPaymentInitiatedEvent.OutputTuple,
    CrossChainPaymentInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorAdded"
  ): TypedContractEvent<
    OperatorAddedEvent.InputTuple,
    OperatorAddedEvent.OutputTuple,
    OperatorAddedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorRemoved"
  ): TypedContractEvent<
    OperatorRemovedEvent.InputTuple,
    OperatorRemovedEvent.OutputTuple,
    OperatorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "CrossChainPaymentCompleted(uint256,address,address,address,uint256,string,string)": TypedContractEvent<
      CrossChainPaymentCompletedEvent.InputTuple,
      CrossChainPaymentCompletedEvent.OutputTuple,
      CrossChainPaymentCompletedEvent.OutputObject
    >;
    CrossChainPaymentCompleted: TypedContractEvent<
      CrossChainPaymentCompletedEvent.InputTuple,
      CrossChainPaymentCompletedEvent.OutputTuple,
      CrossChainPaymentCompletedEvent.OutputObject
    >;

    "CrossChainPaymentFailed(uint256,address,address,string,string)": TypedContractEvent<
      CrossChainPaymentFailedEvent.InputTuple,
      CrossChainPaymentFailedEvent.OutputTuple,
      CrossChainPaymentFailedEvent.OutputObject
    >;
    CrossChainPaymentFailed: TypedContractEvent<
      CrossChainPaymentFailedEvent.InputTuple,
      CrossChainPaymentFailedEvent.OutputTuple,
      CrossChainPaymentFailedEvent.OutputObject
    >;

    "CrossChainPaymentInitiated(uint256,address,address,address,uint256,string,string)": TypedContractEvent<
      CrossChainPaymentInitiatedEvent.InputTuple,
      CrossChainPaymentInitiatedEvent.OutputTuple,
      CrossChainPaymentInitiatedEvent.OutputObject
    >;
    CrossChainPaymentInitiated: TypedContractEvent<
      CrossChainPaymentInitiatedEvent.InputTuple,
      CrossChainPaymentInitiatedEvent.OutputTuple,
      CrossChainPaymentInitiatedEvent.OutputObject
    >;

    "OperatorAdded(address)": TypedContractEvent<
      OperatorAddedEvent.InputTuple,
      OperatorAddedEvent.OutputTuple,
      OperatorAddedEvent.OutputObject
    >;
    OperatorAdded: TypedContractEvent<
      OperatorAddedEvent.InputTuple,
      OperatorAddedEvent.OutputTuple,
      OperatorAddedEvent.OutputObject
    >;

    "OperatorRemoved(address)": TypedContractEvent<
      OperatorRemovedEvent.InputTuple,
      OperatorRemovedEvent.OutputTuple,
      OperatorRemovedEvent.OutputObject
    >;
    OperatorRemoved: TypedContractEvent<
      OperatorRemovedEvent.InputTuple,
      OperatorRemovedEvent.OutputTuple,
      OperatorRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
