/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IOmniPayNotifierInterface extends Interface {
  getFunction(
    nameOrSignature: "notifyPaymentFailure" | "notifyPaymentSuccess"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "notifyPaymentFailure",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "notifyPaymentSuccess",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "notifyPaymentFailure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "notifyPaymentSuccess",
    data: BytesLike
  ): Result;
}

export interface IOmniPayNotifier extends BaseContract {
  connect(runner?: ContractRunner | null): IOmniPayNotifier;
  waitForDeployment(): Promise<this>;

  interface: IOmniPayNotifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  notifyPaymentFailure: TypedContractMethod<
    [
      payer: AddressLike,
      payee: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      paymentRef: string,
      reason: string
    ],
    [void],
    "nonpayable"
  >;

  notifyPaymentSuccess: TypedContractMethod<
    [
      payer: AddressLike,
      payee: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      paymentRef: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "notifyPaymentFailure"
  ): TypedContractMethod<
    [
      payer: AddressLike,
      payee: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      paymentRef: string,
      reason: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "notifyPaymentSuccess"
  ): TypedContractMethod<
    [
      payer: AddressLike,
      payee: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      paymentRef: string
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
