/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPUSHCommInterface,
  IPUSHCommInterfaceInterface,
} from "../../../contracts/OmniPayNotifier.sol/IPUSHCommInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "channel",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "identity",
        type: "bytes",
      },
    ],
    name: "sendNotification",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPUSHCommInterface__factory {
  static readonly abi = _abi;
  static createInterface(): IPUSHCommInterfaceInterface {
    return new Interface(_abi) as IPUSHCommInterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPUSHCommInterface {
    return new Contract(address, _abi, runner) as unknown as IPUSHCommInterface;
  }
}
