/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface OmniPayNotifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "channel"
      | "notifyBeforeRenewal"
      | "notifyPaymentFailure"
      | "notifyPaymentSuccess"
      | "notifySubscriptionCancelled"
      | "notifySubscriptionExecuted"
      | "owner"
      | "pushComm"
      | "renounceOwnership"
      | "setChannel"
      | "setPushComm"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BeforeRenewal"
      | "NotifierConfigured"
      | "OwnershipTransferred"
      | "PaymentFailure"
      | "PaymentSuccess"
      | "PushAttempt"
      | "SubscriptionCancelled"
      | "SubscriptionExecuted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "channel", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "notifyBeforeRenewal",
    values: [BigNumberish, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "notifyPaymentFailure",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "notifyPaymentSuccess",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "notifySubscriptionCancelled",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "notifySubscriptionExecuted",
    values: [
      BigNumberish,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pushComm", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setChannel",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPushComm",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "channel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "notifyBeforeRenewal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "notifyPaymentFailure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "notifyPaymentSuccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "notifySubscriptionCancelled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "notifySubscriptionExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pushComm", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setChannel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPushComm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace BeforeRenewalEvent {
  export type InputTuple = [
    subId: BigNumberish,
    subscriber: AddressLike,
    merchant: AddressLike,
    amount: BigNumberish,
    nextPaymentDue: BigNumberish
  ];
  export type OutputTuple = [
    subId: bigint,
    subscriber: string,
    merchant: string,
    amount: bigint,
    nextPaymentDue: bigint
  ];
  export interface OutputObject {
    subId: bigint;
    subscriber: string;
    merchant: string;
    amount: bigint;
    nextPaymentDue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NotifierConfiguredEvent {
  export type InputTuple = [pushComm: AddressLike, channel: AddressLike];
  export type OutputTuple = [pushComm: string, channel: string];
  export interface OutputObject {
    pushComm: string;
    channel: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentFailureEvent {
  export type InputTuple = [
    payer: AddressLike,
    payee: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    paymentRef: string,
    reason: string
  ];
  export type OutputTuple = [
    payer: string,
    payee: string,
    token: string,
    amount: bigint,
    paymentRef: string,
    reason: string
  ];
  export interface OutputObject {
    payer: string;
    payee: string;
    token: string;
    amount: bigint;
    paymentRef: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentSuccessEvent {
  export type InputTuple = [
    payer: AddressLike,
    payee: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    paymentRef: string
  ];
  export type OutputTuple = [
    payer: string,
    payee: string,
    token: string,
    amount: bigint,
    paymentRef: string
  ];
  export interface OutputObject {
    payer: string;
    payee: string;
    token: string;
    amount: bigint;
    paymentRef: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PushAttemptEvent {
  export type InputTuple = [
    recipient: AddressLike,
    success: boolean,
    identity: BytesLike
  ];
  export type OutputTuple = [
    recipient: string,
    success: boolean,
    identity: string
  ];
  export interface OutputObject {
    recipient: string;
    success: boolean;
    identity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCancelledEvent {
  export type InputTuple = [
    subId: BigNumberish,
    subscriber: AddressLike,
    merchant: AddressLike
  ];
  export type OutputTuple = [
    subId: bigint,
    subscriber: string,
    merchant: string
  ];
  export interface OutputObject {
    subId: bigint;
    subscriber: string;
    merchant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionExecutedEvent {
  export type InputTuple = [
    subId: BigNumberish,
    subscriber: AddressLike,
    merchant: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    nextPaymentDue: BigNumberish
  ];
  export type OutputTuple = [
    subId: bigint,
    subscriber: string,
    merchant: string,
    token: string,
    amount: bigint,
    nextPaymentDue: bigint
  ];
  export interface OutputObject {
    subId: bigint;
    subscriber: string;
    merchant: string;
    token: string;
    amount: bigint;
    nextPaymentDue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OmniPayNotifier extends BaseContract {
  connect(runner?: ContractRunner | null): OmniPayNotifier;
  waitForDeployment(): Promise<this>;

  interface: OmniPayNotifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  channel: TypedContractMethod<[], [string], "view">;

  notifyBeforeRenewal: TypedContractMethod<
    [
      subId: BigNumberish,
      subscriber: AddressLike,
      merchant: AddressLike,
      amount: BigNumberish,
      nextPaymentDue: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  notifyPaymentFailure: TypedContractMethod<
    [
      payer: AddressLike,
      payee: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      paymentRef: string,
      reason: string
    ],
    [void],
    "nonpayable"
  >;

  notifyPaymentSuccess: TypedContractMethod<
    [
      payer: AddressLike,
      payee: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      paymentRef: string
    ],
    [void],
    "nonpayable"
  >;

  notifySubscriptionCancelled: TypedContractMethod<
    [subId: BigNumberish, subscriber: AddressLike, merchant: AddressLike],
    [void],
    "nonpayable"
  >;

  notifySubscriptionExecuted: TypedContractMethod<
    [
      subId: BigNumberish,
      subscriber: AddressLike,
      merchant: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      nextPaymentDue: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pushComm: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setChannel: TypedContractMethod<
    [_channel: AddressLike],
    [void],
    "nonpayable"
  >;

  setPushComm: TypedContractMethod<
    [_pushComm: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "channel"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "notifyBeforeRenewal"
  ): TypedContractMethod<
    [
      subId: BigNumberish,
      subscriber: AddressLike,
      merchant: AddressLike,
      amount: BigNumberish,
      nextPaymentDue: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "notifyPaymentFailure"
  ): TypedContractMethod<
    [
      payer: AddressLike,
      payee: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      paymentRef: string,
      reason: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "notifyPaymentSuccess"
  ): TypedContractMethod<
    [
      payer: AddressLike,
      payee: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      paymentRef: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "notifySubscriptionCancelled"
  ): TypedContractMethod<
    [subId: BigNumberish, subscriber: AddressLike, merchant: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "notifySubscriptionExecuted"
  ): TypedContractMethod<
    [
      subId: BigNumberish,
      subscriber: AddressLike,
      merchant: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      nextPaymentDue: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pushComm"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setChannel"
  ): TypedContractMethod<[_channel: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPushComm"
  ): TypedContractMethod<[_pushComm: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BeforeRenewal"
  ): TypedContractEvent<
    BeforeRenewalEvent.InputTuple,
    BeforeRenewalEvent.OutputTuple,
    BeforeRenewalEvent.OutputObject
  >;
  getEvent(
    key: "NotifierConfigured"
  ): TypedContractEvent<
    NotifierConfiguredEvent.InputTuple,
    NotifierConfiguredEvent.OutputTuple,
    NotifierConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentFailure"
  ): TypedContractEvent<
    PaymentFailureEvent.InputTuple,
    PaymentFailureEvent.OutputTuple,
    PaymentFailureEvent.OutputObject
  >;
  getEvent(
    key: "PaymentSuccess"
  ): TypedContractEvent<
    PaymentSuccessEvent.InputTuple,
    PaymentSuccessEvent.OutputTuple,
    PaymentSuccessEvent.OutputObject
  >;
  getEvent(
    key: "PushAttempt"
  ): TypedContractEvent<
    PushAttemptEvent.InputTuple,
    PushAttemptEvent.OutputTuple,
    PushAttemptEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCancelled"
  ): TypedContractEvent<
    SubscriptionCancelledEvent.InputTuple,
    SubscriptionCancelledEvent.OutputTuple,
    SubscriptionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionExecuted"
  ): TypedContractEvent<
    SubscriptionExecutedEvent.InputTuple,
    SubscriptionExecutedEvent.OutputTuple,
    SubscriptionExecutedEvent.OutputObject
  >;

  filters: {
    "BeforeRenewal(uint256,address,address,uint256,uint256)": TypedContractEvent<
      BeforeRenewalEvent.InputTuple,
      BeforeRenewalEvent.OutputTuple,
      BeforeRenewalEvent.OutputObject
    >;
    BeforeRenewal: TypedContractEvent<
      BeforeRenewalEvent.InputTuple,
      BeforeRenewalEvent.OutputTuple,
      BeforeRenewalEvent.OutputObject
    >;

    "NotifierConfigured(address,address)": TypedContractEvent<
      NotifierConfiguredEvent.InputTuple,
      NotifierConfiguredEvent.OutputTuple,
      NotifierConfiguredEvent.OutputObject
    >;
    NotifierConfigured: TypedContractEvent<
      NotifierConfiguredEvent.InputTuple,
      NotifierConfiguredEvent.OutputTuple,
      NotifierConfiguredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentFailure(address,address,address,uint256,string,string)": TypedContractEvent<
      PaymentFailureEvent.InputTuple,
      PaymentFailureEvent.OutputTuple,
      PaymentFailureEvent.OutputObject
    >;
    PaymentFailure: TypedContractEvent<
      PaymentFailureEvent.InputTuple,
      PaymentFailureEvent.OutputTuple,
      PaymentFailureEvent.OutputObject
    >;

    "PaymentSuccess(address,address,address,uint256,string)": TypedContractEvent<
      PaymentSuccessEvent.InputTuple,
      PaymentSuccessEvent.OutputTuple,
      PaymentSuccessEvent.OutputObject
    >;
    PaymentSuccess: TypedContractEvent<
      PaymentSuccessEvent.InputTuple,
      PaymentSuccessEvent.OutputTuple,
      PaymentSuccessEvent.OutputObject
    >;

    "PushAttempt(address,bool,bytes)": TypedContractEvent<
      PushAttemptEvent.InputTuple,
      PushAttemptEvent.OutputTuple,
      PushAttemptEvent.OutputObject
    >;
    PushAttempt: TypedContractEvent<
      PushAttemptEvent.InputTuple,
      PushAttemptEvent.OutputTuple,
      PushAttemptEvent.OutputObject
    >;

    "SubscriptionCancelled(uint256,address,address)": TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;
    SubscriptionCancelled: TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;

    "SubscriptionExecuted(uint256,address,address,address,uint256,uint256)": TypedContractEvent<
      SubscriptionExecutedEvent.InputTuple,
      SubscriptionExecutedEvent.OutputTuple,
      SubscriptionExecutedEvent.OutputObject
    >;
    SubscriptionExecuted: TypedContractEvent<
      SubscriptionExecutedEvent.InputTuple,
      SubscriptionExecutedEvent.OutputTuple,
      SubscriptionExecutedEvent.OutputObject
    >;
  };
}
