/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOmniPayNotifierSub,
  IOmniPayNotifierSubInterface,
} from "../../../contracts/OmniPaySubscription.sol/IOmniPayNotifierSub";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "subId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "subscriber",
        type: "address",
      },
      {
        internalType: "address",
        name: "merchant",
        type: "address",
      },
    ],
    name: "notifySubscriptionCancelled",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "subId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "subscriber",
        type: "address",
      },
      {
        internalType: "address",
        name: "merchant",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "nextPaymentDue",
        type: "uint256",
      },
    ],
    name: "notifySubscriptionExecuted",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOmniPayNotifierSub__factory {
  static readonly abi = _abi;
  static createInterface(): IOmniPayNotifierSubInterface {
    return new Interface(_abi) as IOmniPayNotifierSubInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOmniPayNotifierSub {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IOmniPayNotifierSub;
  }
}
